apiVersion: batch/v1
kind: Job
metadata:
  name: storage-create
  namespace: {{ .Release.Namespace }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: storage-create
    spec:
      serviceAccountName: storage-create
      containers:
      - name: storage-create
        image: azurecr/azure-cli
        env:
        - name: azure_service_principal_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_service_principal_name
        - name: azure_service_principal_key
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_service_principal_key
        - name: azure_storage_subscription
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_subscription
        - name: azure_storage_resource_group
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_resource_group
        - name: azure_storage_account_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_account_name
        - name: azure_file_share_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_file_share_name
        - name: azure_storage_ad_tenant
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_ad_tenant
        - name: azure_storage_account_location
          value: {{ index .Values "storage-create" "azure_storage_account_location" }}
        command:
        - "bin/bash"
        - "-c" 
        - "apk add --no-cache wget && touch /tmp/run.sh && chmod +x /tmp/run.sh && echo H4sIAF3KT1sAA5VVXU/bMBR996/wvEjdJFyP0bGtopPGBHtAGtJgexlTcB3TmAY72E4nYPz3XTtpSAOlWl6a+N577vG5H335gk2VZlPucsRvKytTJ+1CCZmWVmmhSl6kml/JSbK91j6XN5Pk7dLsjeUzmfIs9VJz7SfJTs/kqqkTVpVeGT1JRrhnttKZykKGmTVVOUne9ZGFMJX2Da3dxnqhCnDJObzWhvco/LqSC/j4gAojeJ3wI0JS5AaTLo8xTtaTJE1ACwje7TtBwAAXZqY0prRRh7bqYFq10E8qi2m53gGkBdBayD7DVuGQvxEFO+kDiw755y4WqTeGFkJYyT3QopFdP2lHfHBZ1orGWvWdVysZeM0rfOK5zrjN0q/fT+BoWRecLN/QmnrHNnv1BGEwOFwoBzd/dNtVvrMNDP/iy2s8GP5683u44EUlB3DiZIYHjp0RxmaD1wjBqMjdUd1k57EvICt5Ji0BkDoIXrzFFPDO9OB8iRTutREInDbgxLgwBXEIHiP2BmQtWrclonvbEK24PSioYkOThn5df4OO46beQujox/5Benp8dPANqr7HFtwyW2nmJNDxjs2rqbRaeumGyrBmchoE5s1caqgVNBT+hOuQ4aWDLtvbOzg+RHcYHsJL9VNaFwZ8jMlim2zF44x7Dgd3CNcPiSwbkk2GWkGISjrtQLaeC4kV7ESE715AW72uY88SI+7rQDJXOgvcT+INGzhyJT3vX6JeXsG3YUWF0VqKuN62Vr3qtRYYdJZcN62/KaP9uOTXFdjuURA1qt3RGqE/s7CNwpTnkmfSTr4YDSvL01MAGPOyLFQ98izWBjaOoSKXYk6FtF5dBGvoLsFXDv6vFwQfCutbDph8rnxurLrl9d7flyCrxclDvxFwLo3zNKi+0j0k9750Y9bNmMkLXhV+PBrtMOgotthmrWyOPUi4ZAv/F/8AHpBDzXUHAAA= | base64 -d | gzip -d >> /tmp/run.sh && cd /tmp && ./run.sh $azure_service_principal_name $azure_service_principal_key $azure_storage_ad_tenant $azure_storage_subscription $azure_storage_resource_group $azure_storage_account_name $azure_file_share_name '{{ .Release.Namespace }}' $azure_storage_account_location"
      restartPolicy: Never
